namespace Lab3;

public enum TokenType
{
    START, FINISH,
    FUNCTION, MAIN, RETURN,
    VAR, TRUE, FALSE, NULL,
    COMMA, SEMICOLON,
    IDENTIFIER, NUMBER_VALUE, STRING_VALUE,
    MESSAGE, INPUT, OUTPUT,
    IF, ELSE, ELIF,
    ADDITION, SUBTRACTION, INCREMENT, DECREMENT, MULTIPLICATION, DIVISION, POW, 
    GREATER, LESS, GREATER_OR_EQUAL, LESS_OR_EQUAL,
    ASSIGN, EQUAL, NOT, NOT_EQUAL,
    OPEN_PARENTHESIS, OPEN_BRACKET,OPEN_BRACE,
    CLOSE_PARENTHESIS, CLOSE_BRACKET, CLOSE_BRACE,
    ILLEGAL, EOF,
}
